import type { Transaction } from './context/TransactionsContext';

export const transactions: Transaction[] = [
  {
    key: '1',
    name: 'мама',
    date: new Date().toISOString(),
    type: 'пополнение',
    amount: 20,
    description: 'desc',
  },
  {
    key: '2',
    name: 'папа',
    date: new Date().toISOString(),
    type: 'пополнение',
    amount: 202,
    description: 'desc',
  },
  {
    key: '3',
    name: 'толя',
    date: new Date().toISOString(),
    type: 'списание',
    amount: 202,
    description: 'desc',
  },
  {
    key: '4',
    name: 'мама',
    date: new Date().toISOString(),
    type: 'пополнение',
    amount: 210,
    description: 'desc',
  },
  {
    key: '5',
    name: 'тёма',
    date: new Date().toISOString(),
    type: 'списание',
    amount: 109,
    description: 'desc',
  },
  {
    key: '6',
    name: 'папа',
    date: new Date().toISOString(),
    type: 'пополнение',
    amount: 2000,
    description: 'desc',
  },
  {
    key: '7',
    name: 'мама',
    date: new Date().toISOString(),
    type: 'пополнение',
    amount: 10,
    description: 'desc',
  },
  {
    key: '8',
    name: 'тёма',
    date: new Date().toISOString(),
    type: 'пополнение',
    amount: 10,
    description: 'desc',
  },
  {
    key: '9',
    name: 'мама',
    date: new Date().toISOString(),
    type: 'пополнение',
    amount: 10,
    description: 'desc',
  },
  {
    key: '10',
    name: 'тёма',
    date: new Date().toISOString(),
    type: 'пополнение',
    amount: 10,
    description: 'desc',
  },
  {
    key: '11',
    name: 'мама',
    date: new Date().toISOString(),
    type: 'пополнение',
    amount: 10,
    description: 'desc',
  },
];
